name: estrella_guia
description: "App de reflexiones navideñas y familiares EstrellaGuía."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  table_calendar: ^3.0.10
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_dotenv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Actualizado a la versión más estable para tu SDK

flutter:
  uses-material-design: true

  # Sección de recursos: Asegúrate de que el archivo .env esté en la raíz del proyecto
  assets:
    - .env